from tkinter import *
from tkinter.ttk import *
import time
import tkinter
import tkinter.font as font
import tkinter as tk

# creacion de la ventana
ventanaes =  Tk();
ventanaes.title("SISTEMA FOTONICO 1D")
ventanaes.iconbitmap("isotipo.ico")
ventanaes.configure(bg='white')
ventanaes.resizable(False, False)
# redimensionar nuestra ventana
ventanaes.geometry("600x989")

tituloVentanaSimulada = Label(ventanaes, text="Datos de la estructura simulada", background="white")
tituloVentanaSimulada.config(font=("Courier Bold",20))
nombreArchivo = Label(ventanaes, text="Nombre del archivo:", background="white")
nombreArchivo.config(font=("Courier Bold", 14))
nombreArchivo.place(x = 100, y =60 )
datoNombreArchivo = Label(ventanaes, text="xxxxxx", background="white")
datoNombreArchivo.config(font=("Courier Bold", 14))
datoNombreArchivo.place(x=430, y=60)
anchoBanda = Label(ventanaes, text="Ancho de banda para la frecuencia:", background="white")
anchoBanda.config(font=("Courier Bold", 14))
anchoBanda.place(x = 100, y = 100)
datoAnchoBanda = Label(ventanaes, text="xxxxxx", background="white")
datoAnchoBanda.config(font=("Courier Bold", 14))
datoAnchoBanda.place(x = 430, y = 100)
frecuenciaInicial = Label(ventanaes, text="Frecuencia inicial:", background ="white")
frecuenciaInicial.config(font = ("Courier Bold", 14))
frecuenciaInicial.place(x = 100, y = 140)
datoFrecuenciaInicial = Label(ventanaes, text="xxxxxx", background ="white")
datoFrecuenciaInicial.config(font = ("Courier Bold", 14))
datoFrecuenciaInicial.place(x = 430, y = 140)
frecuenciaFinal = Label(ventanaes, text="Frecuencia final:", background ="white")
frecuenciaFinal.config(font = ("Courier Bold", 14))
frecuenciaFinal.place(x = 100, y = 180)
datoFrecuenciaFinal = Label(ventanaes, text="xxxxxx", background ="white")
datoFrecuenciaFinal.config(font = ("Courier Bold", 14))
datoFrecuenciaFinal.place(x = 430, y = 180)
numeroParticionesFrecuencia = Label(ventanaes, text="Número de particiones de frecuencia:", background="white")
numeroParticionesFrecuencia.config(font=("Courier Bold", 14))
numeroParticionesFrecuencia.place(x = 100, y = 220)
datoNumeroParticionesFrecuencia = Label(ventanaes, text="xxxxxx", background="white")
datoNumeroParticionesFrecuencia.config(font=("Courier Bold", 14))
datoNumeroParticionesFrecuencia.place(x = 430, y = 220)
numeroTotalPeriodos = Label(ventanaes, text="Número total de períodos:", background="white")
numeroTotalPeriodos.config(font=("Courier Bold", 14))
numeroTotalPeriodos.place(x = 100, y = 260)
datoNumeroTotalPeriodos = Label(ventanaes, text="xxxxxx", background="white")
datoNumeroTotalPeriodos.config(font=("Courier Bold", 14))
datoNumeroTotalPeriodos.place(x = 430, y = 260)
numeroCapasEstructura = Label(ventanaes, text="Número de capas de la estructura:", background="white")
numeroCapasEstructura.config(font=("Courier Bold", 14))
numeroCapasEstructura.place(x = 100, y =320)
datoNumeroCapasEstructura = Label(ventanaes, text="xxxxxx", background="white")
datoNumeroCapasEstructura.config(font=("Courier Bold", 14))
datoNumeroCapasEstructura.place(x = 430, y =320)
capa =Label(ventanaes, text ="Capa n", background="white")
capa.config(font=("Courier Bold", 17))
capa.place(x=100, y =380)
anchoCapa = Label(ventanaes, text ="Ancho de la capa n:", background="white")
anchoCapa.config(font =("Courier Bold", 14))
anchoCapa.place(x =100, y =420)
datoAnchoCapa = Label(ventanaes, text ="xxxxxx", background="white")
datoAnchoCapa.config(font =("Courier Bold", 14))
datoAnchoCapa.place(x =430, y =420)
tipoPerfil = Label(ventanaes, text ="Tipo de perfil de la capa n:", background="white")
tipoPerfil.config(font =("Courier Bold", 14))
tipoPerfil.place(x =100, y =460)
datoTipoPerfil = Label(ventanaes, text ="xxxxxx", background="white")
datoTipoPerfil.config(font =("Courier Bold", 14))
datoTipoPerfil.place(x = 430, y =460)
parametrosTipoPerfil = Label(ventanaes, text ="Parametros del tipo de perfil:", background="white")
parametrosTipoPerfil.config(font =("Courier Bold", 14))
parametrosTipoPerfil.place(x =100, y =500)
datoParametrosTipoPerfil = Label(ventanaes, text ="xxxxxx", background="white")
datoParametrosTipoPerfil.config(font =("Courier Bold", 14))
datoParametrosTipoPerfil.place(x =430, y =500)
parametroA = Label(ventanaes, text ="A", background="white")
parametroA.config(font =("Courier Bold", 14))
parametroA.place(x=140, y = 540)
datoParametroA = Label(ventanaes, text ="xx", background="white")
datoParametroA.config(font =("Courier Bold", 14))
datoParametroA.place(x=140, y = 580)
parametroB = Label(ventanaes, text ="B", background="white")
parametroB.config(font =("Courier Bold", 14))
parametroB.place(x=280, y = 540)
datoParametroB = Label(ventanaes, text ="xx", background="white")
datoParametroB.config(font =("Courier Bold", 14))
datoParametroB.place(x=280, y = 580)
parametroC = Label(ventanaes, text ="C", background="white")
parametroC.config(font =("Courier Bold", 14))
parametroC.place(x=420, y = 540)
datoParametroC = Label(ventanaes, text ="xx", background="white")
datoParametroC.config(font =("Courier Bold", 14))
datoParametroC.place(x=420, y = 580)
numeroParticiones = Label(ventanaes, text ="Número de particiones:", background="white")
numeroParticiones.config(font =("Courier Bold", 14))
numeroParticiones.place(x=100, y = 620)
datoNumeroParticiones = Label(ventanaes, text ="xxxxxx", background="white")
datoNumeroParticiones.config(font =("Courier Bold", 14))
datoNumeroParticiones.place(x=430, y = 620)
pregunta = Label(ventanaes, text ="¿Está seguro que desea realizar la simulación?", background="white")
pregunta.config(font =("Courier Bold", 17))
pregunta.place(x=50, y = 680)
tituloVentanaSimulada.pack()




ventanaes.mainloop()